### ISSUE TITLE
Widget Request - suspect pool

### ISSUE THREAD

**Issue by datalover916** [tarakc02/discoveryengine#20]
Tarak,

We have not been able to utilize suspect pool area in WEBI because there is no object for it. Is there anyway to add the comment/text as a widget in_suspect_pool() - the main advantage to this also would be to be able to search the various existing pools in the brainstorm_bot. For example, I know there are multiple women in technology ones that Bob and I created over the past few years.

Lucila and I are currently working on two pools for the nor cal team, and with changing portfolios it would be great to isolate those who are not/ no longer in a portfolio, and well as narrow by alumni, or city, or degree, etc.

Let us know if you need more info, or if it is impossible to add this widget.

Thanks!!!

**Comment by tarakc02** [comment]
I can definitely add a widget that does text search of the suspect pool comments -- it would make a nice addition to the other text-search widgets (such as `fund_text_contains`, `contact_text_contains`, and `research_miner`). However, the `brainstorm_bot` can only search codes/descriptions from validated code tables (for Suspect Pools, that would include "Source," "Pool," "Stage," and "Unit," but not the comments). I'm looking at building another bot that utilizes all of the plain text search tools, unfortunately there's no good way to make those searches part of the `brainstorm_bot` at this point.

**Comment by tarakc02** [comment]
Documenting here some of the comments from an email chain about this issue:
* When determining what constitutes a single suspect pool (vs. multiples), we should count anything with the same comment + unit as the same pool.
* AIM may eventually expand the data warehouse to create explicit suspect pool objects, which we can then query like anything else (eg saved lists). If/when that happens, we'll update the suspect pool widget to use the new objects.
