### ISSUE TITLE
lives_in_city/works_in_city

### ISSUE THREAD

**Issue by datalover916** [tarakc02/discoveryengine#22]
I have had a need to get down to the city level twice, so I figured I would submit this.  It is particularly useful when clients say, hey I am going to X event in Claremont, can I get some prospects to try to visit before or after.  Now, I pull  based on county, but then loose the speed of the disco engine because then have to run a cadsmart report and narrow by city.

With this in mind, something really cool, and I am not sure if it is w/in the realm of possibility, but to be able to do a search of X miles within/from a city - a radius would be cool.  I know it is a problem in the bay area and LA, where they don't want to invite people too far away, so the MSA/County designations are often too inclusive, but the city is sometimes too small, or you don't know like little tiny cities nearby.

**Comment by tarakc02** [comment]
Oh, I'm so glad you've submitted this issue. We can, in fact, do a radius "within x miles" widget. I'm a bit swamped at the moment, but will try to get to this update early next week, if not sooner.

**Comment by cwolfsonseeley** [comment]
I've put it on my to do list, too! (If you have hints about the radius, Tarak, let me know.)

**Comment by tarakc02** [comment]
Thanks Caleb! I've already got the radius query set up, from some experimenting I was doing when AIM exposed the lat/long information in the data warehouse. Details are here: https://docs.oracle.com/cd/B19306_01/appdev.102/b14255/sdo_operat.htm#i77653  

I don't want to add a separate widget for city, as I think MSA, county, zip, and now radius are plenty. But I'm happy to be convinced to change my mind.

**Comment by datalover916** [comment]
How would the radius widget work, if not based on city? zip?

**Comment by tarakc02** [comment]
Enter any address or location. For instance `lives_near("UC Berkeley", miles = 25)` or `works_near("1234 Main Street, Anytown CA 94720", miles = 15)` or, finally (I think this speaks to your question, `lives_near("Lafayette, CA", miles = 35)`. Sorry for the confusion, I meant that I don't want to add a separate `lives_in_city` or `works_in_city` widget -- you could definitely use the radius widget with a city name (the widget calculates distances from the center of the city).

**Comment by tarakc02** [comment]
Ok, I'm (finally) closing this issue. The new widgets are available as `lives_near` and `works_near`, added in commit [f8adc35](https://github.com/tarakc02/discoveryengine/commit/f8adc35a3fdf440bf6ef58965a42dcfafea39f14). Let me know if you have further questions, I'll look to update the disco docs
